/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/cltx/clienthub/cmd/libclienthub */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

typedef void (*chub_log_callback)(int level, const char* msg);
typedef void (*chub_status_callback)(int handle, int status, const char* detail);
typedef void (*chub_event_callback)(int handle, const char* eventJSON);

static void call_log_cb(chub_log_callback fn, int level, const char* msg) {
    if (fn) fn(level, msg);
}
static void call_status_cb(chub_status_callback fn, int handle, int status, const char* detail) {
    if (fn) fn(handle, status, detail);
}
static void call_event_cb(chub_event_callback fn, int handle, const char* eventJSON) {
    if (fn) fn(handle, eventJSON);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void CHubInit(void);
extern void CHubFree(void);
extern void CHubSetLogCallback(chub_log_callback fn);
extern void CHubSetStatusCallback(chub_status_callback fn);
extern void CHubSetEventCallback(chub_event_callback fn);
extern int CHubClientCreate(char* configJSON);
extern void CHubClientStart(int handle);
extern void CHubClientStop(int handle);
extern void CHubClientDestroy(int handle);
extern char* CHubClientGetStatus(int handle);
extern int CHubManagerCreate(char* addr, char* secret);
extern char* CHubManagerListClients(int handle);
extern char* CHubManagerListTunnels(int handle);
extern char* CHubManagerListForwards(int handle);
extern char* CHubManagerAddForward(int handle, char* paramsJSON);
extern char* CHubManagerRemoveForward(int handle, char* paramsJSON);
extern char* CHubManagerKickClient(int handle, char* name);
extern char* CHubManagerStatus(int handle);
extern char* CHubManagerListExpose(int handle, char* clientName);
extern char* CHubManagerAddExpose(int handle, char* paramsJSON);
extern char* CHubManagerRemoveExpose(int handle, char* paramsJSON);
extern void CHubManagerDestroy(int handle);
extern void CHubFreeString(char* s);

#ifdef __cplusplus
}
#endif
